# Generated by Django 2.2.3 on 2019-07-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_auto_20190201_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='location',
            field=models.CharField(choices=[('ruet', 'RUET, Rajshahi'), ('sust', 'SUST, Sylhet'), ('rmmc', 'RmMC, Rangamati')], max_length=55),
        ),
    ]
