# Generated by Django 2.1.5 on 2019-02-01 06:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20190201_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('roll', models.CharField(blank=True, max_length=20)),
                ('dept', models.CharField(blank=True, max_length=20)),
                ('txnid', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=3)),
                ('units', models.IntegerField()),
                ('payMethod', models.CharField(max_length=20)),
                ('user_id', models.IntegerField(max_length=4)),
                ('order_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_valid', models.BooleanField(blank=True, default=0)),
                ('is_delivered', models.BooleanField(blank=True, default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product')),
            ],
        ),
    ]
