# Generated by Django 2.2.1 on 2019-05-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dept',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
