# Generated by Django 2.1.5 on 2019-01-30 19:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('color', models.TextField()),
                ('units_s', models.IntegerField(blank=True, default=0)),
                ('units_m', models.IntegerField(blank=True, default=0)),
                ('units_l', models.IntegerField(blank=True, default=0)),
                ('units_xl', models.IntegerField(blank=True, default=0)),
                ('units_xxl', models.IntegerField(blank=True, default=0)),
                ('units_3xl', models.IntegerField(blank=True, default=0)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('release_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agent.Agent')),
            ],
        ),
    ]
