# Generated by Django 2.1.5 on 2019-01-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190131_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bkash_no',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='product',
            name='rocket_no',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
