# Generated by Django 2.1.5 on 2019-02-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190201_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='l',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='m',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='s',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='xl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='xxl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='xxxl',
            field=models.BooleanField(default=True),
        ),
    ]
